########################################################################
# https://wiki.cachyos.org/configuration/gaming/#environment-variables #
########################################################################

# Graphics & Upscaling
PROTON_FSR4_UPGRADE=1
PROTON_FSR4_RDNA3_UPGRADE=1
PROTON_XESS_UPGRADE=1

# Display & HDR
PROTON_ENABLE_WAYLAND=1
PROTON_NO_WM_DECORATION=1
PROTON_ENABLE_HDR=1

# Performance & Caching
PROTON_USE_NTSYNC=1 # Use lsof /dev/ntsync in game

##############
# Raytracing #
##############

RADV_PERFTEST=rt
VKD3D_CONFIG=dxr11
