# Add your additional Hyprland configurations here
#
# This is an additional key binding
# bind = $mainMod CTRL, up, workspace, empty
#
# Example for xwayland
# xwayland {
#   force_zero_scaling = true
# }

# qt5ct environment variable
# env = QT_QPA_PLATFORMTHEME,qt5ct

# SDL version
env = SDL_VIDEODRIVER,wayland
# env = WLR_DRM_NO_ATOMIC,1
# env = SDL_VIDEODRIVER,x11

# Blur for waybar
#layerrule = blur, waybar

###################
# palilo settings #
###################

monitor=DP-1, 2560x1440@239.76, 0x0, 1

# vim-like
unbind= $mainMod, J
unbind= $mainMod, K
unbind= $mainMod, G # window group? wtf?
bind = $mainMod, J, movefocus, l # Move focus left
bind = $mainMod, K, movefocus, r # Move focus right
bind = $mainMod SHIFT, J, movewindow, l
bind = $mainMod SHIFT, K, movewindow, r

# discord
exec-once = discord

# kime
exec-once = kime
env = XDG_CURRENT_DESKTOP,Hyprland
env = GTK_IM_MODULE,kime
env = QT_IM_MODULE,kime
env = XMODIFIERS,@im=kime

# No Hardware Cursor
cursor {
    no_hardware_cursors = false
}

input {
    # activate 한/영 key
    kb_options = ctrl:nocaps,korean:ralt_hangul,korean:rctrl_hanja
    # do not focus window by mouse
    follow_mouse = 2
    float_switch_override_focus = 0
}

misc {
    # controls the VRR (Adaptive Sync) of your monitors.
    # 0 - off, 1 - on, 2 - fullscreen only, 3 - fullscreen with video or game
    vrr = 3
}

render {
    # Direct scanout attempts to reduce lag when there is only one fullscreen application on a screen
    # 0 - off, 1 - on, 2 - auto (on with content type ‘game’)
    direct_scanout = 2
}
